In [1]:
from datasets import load_dataset
from collections import Counter
import gc
import ast
import pandas as pd

In [2]:
full_val_df = pd.read_parquet("data/danbooru2025_val.parquet")
full_val_df

,id,media_asset_created_at,score,rating,media_asset_file_size,tag_string_general,tag_string_character,tag_string_copyright,image_url,tags,image_path
0,3803458,2020-02-29T02:04:09.022-05:00,65,s,623996,1girl antenna_hair armpits bed_sheet blush bre...,al_azif_(demonbane),demonbane,https://cdn.donmai.us/360x360/57/a8/57a82bf4a1...,"[1girl, antenna_hair, armpits, bed_sheet, blus...",data/images/danbooru2025_val/3803458.jpg
1,7615873,2024-05-08T16:52:36.138-04:00,106,e,126497,1boy 1girl all_fours anal ass barefoot black_t...,megumin satou_kazuma,kono_subarashii_sekai_ni_shukufuku_wo!,https://cdn.donmai.us/360x360/04/5e/045e482079...,"[1boy, 1girl, all_fours, anal, ass, barefoot, ...",data/images/danbooru2025_val/7615873.jpg
2,5807689,2022-11-08T06:41:09.289-05:00,99,s,295115,1girl alternate_hairstyle breasts cleavage clo...,arisugawa_natsuha,idolmaster idolmaster_shiny_colors,https://cdn.donmai.us/360x360/dd/58/dd589e8223...,"[1girl, alternate_hairstyle, breasts, cleavage...",data/images/danbooru2025_val/5807689.jpg
3,5771329,2022-10-24T13:40:25.390-04:00,135,e,2100081,1boy 1girl :o arm_grab bar_censor bouncing_bre...,,original,https://cdn.donmai.us/360x360/7e/db/7edb0f7795...,"[1boy, 1girl, :o, arm_grab, bar_censor, bounci...",data/images/danbooru2025_val/5771329.jpg
4,2987219,2018-01-14T16:47:46.466-05:00,62,q,154001,1girl armor black_panties blue_eyes blue_hair ...,nanami_yachiyo,magia_record:_mahou_shoujo_madoka_magica_gaide...,https://cdn.donmai.us/360x360/ff/7e/ff7edf51b7...,"[1girl, armor, black_panties, blue_eyes, blue_...",data/images/danbooru2025_val/2987219.jpg
...,...,...,...,...,...,...,...,...,...,...,...
99995,5599936,2022-08-17T22:49:56.764-04:00,53,s,577595,1girl ahoge animal_ears bare_legs black_skirt ...,,original,https://cdn.donmai.us/360x360/5b/62/5b620ccca4...,"[1girl, ahoge, animal_ears, bare_legs, black_s...",data/images/danbooru2025_val/5599936.jpg
99996,8643081,2024-12-31T10:01:59.979-05:00,143,e,9777813,1boy 1girl :q against_glass anus ass breasts c...,kita_ikuyo,bocchi_the_rock!,https://cdn.donmai.us/360x360/c6/73/c673f9a7f9...,"[1boy, 1girl, :q, against_glass, anus, ass, br...",data/images/danbooru2025_val/8643081.jpg
99997,6042767,2023-02-04T16:56:08.190-05:00,231,e,5237793,1boy 1girl ? animal_ears anus ass bar_censor b...,tsunomaki_watame,hololive,https://cdn.donmai.us/360x360/e9/3a/e93ae304c9...,"[1boy, 1girl, ?, animal_ears, anus, ass, bar_c...",data/images/danbooru2025_val/6042767.jpg
99998,5870341,2022-12-03T09:46:20.261-05:00,52,s,604539,1girl body_freckles bra bracelet breasts cleav...,beelzebub_(helltaker),helltaker,https://cdn.donmai.us/360x360/22/0b/220bd87446...,"[1girl, body_freckles, bra, bracelet, breasts,...",data/images/danbooru2025_val/5870341.jpg
99999,7823524,2024-07-07T11:00:01.122-04:00,134,q,2073475,1girl black_footwear black_pantyhose breasts f...,ellen_joe,zenless_zone_zero,https://cdn.donmai.us/360x360/82/43/82433ce2bb...,"[1girl, black_footwear, black_pantyhose, breas...",data/images/danbooru2025_val/7823524.jpg

In [3]:
# convert the datetime col
full_val_df["media_asset_created_at"] = pd.to_datetime(
    full_val_df["media_asset_created_at"],
    utc=True,
)

In [4]:
# get all tags from a DF
def get_tags(df_):
    all_tags = Counter()
    for tags in df_["tags"]:
        all_tags.update(tags)
    return all_tags

In [5]:
# all tags after 2024-02
new_df = full_val_df[full_val_df["media_asset_created_at"] >= pd.Timestamp("2024-03-01", tz="UTC")]
new_tags = get_tags(new_df)
len(new_tags)

10386

In [7]:
for tag in new_tags:
    no_text = True
    for c in tag:
        if c.isalpha():
            no_text = False
            break
    if no_text:
        print(f"tag: {tag}, count: {new_tags[tag]}")

tag: >_<, count: 41
tag: ?, count: 216
tag: :3, count: 178
tag: !?, count: 57
tag: !, count: 74
tag: 69, count: 14
tag: +++, count: 15
tag: @_@, count: 161
tag: :>, count: 18
tag: :>=, count: 36
tag: :/, count: 44
tag: ^_^, count: 70
tag: :|, count: 13
tag: =_=, count: 15
tag: ..., count: 91
tag: ^^^, count: 87
tag: !!, count: 29
tag: 3:, count: 13
tag: <|>_<|>, count: 6
tag: +_+, count: 32
tag: :<, count: 31
tag: >:), count: 10
tag: ...?, count: 1
tag: >:(, count: 7
tag: 2024, count: 14
tag: \||/, count: 15
tag: ;), count: 29
tag: ??, count: 31
tag: 2025, count: 13
tag: |_|, count: 4
tag: ;3, count: 3
tag: 0_0, count: 2
tag: 2023, count: 2

In [8]:
# most popular tags
stags = sorted((-c, t) for t, c in new_tags.items())
stags = [t.replace("_", " ") for c, t in stags][:1000]
", ".join(stags)

"1girl, breasts, long hair, looking at viewer, solo, blush, large breasts, smile, navel, open mouth, nipples, simple background, black hair, thighs, white background, 1boy, cleavage, hair ornament, ass, animal ears, blue eyes, shirt, bare shoulders, blue archive, hetero, sweat, very long hair, hair between eyes, gloves, multicolored hair, nude, short hair, red eyes, censored, underwear, blonde hair, thighhighs, penis, halo, collarbone, closed mouth, jewelry, swimsuit, multiple girls, holding, panties, pussy, long sleeves, tail, skirt, bikini, sitting, heart, purple eyes, stomach, brown hair, medium breasts, sex, dress, huge breasts, white shirt, virtual youtuber, standing, alternate costume, blue hair, 2girls, white hair, pink hair, indoors, lying, grey hair, jacket, bow, earrings, solo focus, completely nude, yellow eyes, twintails, official alternate costume, original, choker, green eyes, sidelocks, pantyhose, small breasts, cowboy shot, hololive, tongue, ahoge, mosaic censoring, cum, black gloves, purple hair, red hair, braid, teeth, ponytail, ribbon, horns, parted lips, vaginal, tongue out, mole, hat, spread legs, zenless zone zero, barefoot, dark skin, black thighhighs, feet, uncensored, armpits, artist name, streaked hair, full body, leotard, nail polish, open clothes, hairband, bar censor, pointy ears, from behind, toes, on back, speech bubble, black choker, two-tone hair, shorts, outdoors, rabbit ears, animal ear fluff, looking back, brown eyes, medium hair, closed eyes, bra, pubic hair, hair over one eye, hair ribbon, pov, anus, flower, genshin impact, black skirt, clothes lift, black panties, fake animal ears, english text, thigh strap, honkai (series), green hair, upper body, hairclip, soles, elbow gloves, honkai: star rail, symbol-shaped pupils, skindentation, on bed, dark-skinned female, black pantyhose, blunt bangs, erection, hand up, sleeveless, one eye closed, pink eyes, hair intakes, white thighhighs, highleg, arms up, multiple views, school uniform, mole under eye, colored inner hair, fingernails, sideboob, sky, crop top, playboy bunny, black bikini, thick thighs, blurry, high heels, female pubic hair, detached sleeves, hair bun, azur lane, bowtie, hololive english, white gloves, covered navel, grin, testicles, white panties, off shoulder, short sleeves, cum in pussy, pants, pleated skirt, cat ears, black dress, wet, collared shirt, hair flower, detached collar, wings, pussy juice, strapless, hair bow, collar, frills, oral, fang, sex from behind, groping, midriff, necktie, covered nipples, torn clothes, day, :d, pillow, from side, blurry background, goddess of victory: nikke, black jacket, see-through clothes, yuri, legs, white dress, fate (series), twitter username, upper teeth only, monochrome, bare legs, parted bangs, black leotard, arm up, clothing cutout, orange hair, cum on body, alternate breast size, open jacket, fellatio, fox ears, heart-shaped pupils, socks, straddling, necklace, black footwear, groin, blue sky, sweatdrop, blue halo, grey background, weapon, white bikini, underboob, fate/grand order, fingerless gloves, glasses, looking at another, tattoo, v, back, saliva, black shorts, comic, signature, food, shoes, girl on top, greyscale, black shirt, bed sheet, miniskirt, areola slip, ass visible through thighs, black bra, grey eyes, multiple boys, orange eyes, bottomless, cameltoe, toenails, belt, piercing, wrist cuffs, dark-skinned male, demon horns, water, sweater, halterneck, boots, grabbing another's breast, feet out of frame, black hairband, cloud, strapless leotard, bracelet, maid headdress, bare arms, gradient hair, short shorts, fox girl, black nails, japanese clothes, ass focus, leaning forward, rabbit tail, breasts out, bright pupils, side-tie bikini bottom, one-piece swimsuit, on side, squatting, highleg leotard, eyewear on head, idolmaster, mole on breast, group sex, patreon username, phone, two side up, shiny skin, from below, futanari, 3girls, cup, shirt lift, no panties, clothes pull, pokemon, bent over, clothed female nude male, aqua eyes, half-closed eyes, bell, no shoes, curvy, motion lines, sunglasses, kneeling, ejaculation, black eyes, open shirt, white pupils, side ponytail, red nails, beach, steaming body, twin braids, thigh gap, cat girl, elf, makeup, cowgirl position, bed, trembling, cat tail, black bow, double bun, eyelashes, apron, pink halo, nose blush, paizuri, from above, sex toy, maid, mature female, all fours, extra ears, breast press, arm support, crossed bangs, no bra, embarrassed, hand on own hip, chinese clothes, lifting own clothes, spoken heart, arknights, veins, window, fur trim, black hat, cellphone, sleeveless dress, coat, large penis, sailor collar, black pants, holding weapon, sensei (blue archive), anal, hands up, bound, mask, striped clothes, fake tail, bodysuit, fishnets, clothing aside, looking to the side, red bow, clenched teeth, condom, facial mark, puffy sleeves, demon girl, red halo, black ribbon, skirt lift, pelvic curtain, black horns, kimono, :o, sousou no frieren, high ponytail, fox tail, torn pantyhose, clothed sex, on stomach, topless, string bikini, foot focus, blue skirt, hood, star (symbol), aqua hair, red ribbon, arms behind head, blue bow, breasts apart, cosplay, steam, restrained, holding phone, garter straps, sleeveless shirt, blue nails, ocean, skin fang, smartphone, x hair ornament, heterochromia, china dress, looking down, male pubic hair, alternate hairstyle, cum on breasts, tan, wide hips, cleft of venus, thong, arms behind back, revealing clothes, touhou, bouncing breasts, veiny penis, pink nails, 2boys, colored skin, tears, after sex, single thighhigh, v-shaped eyebrows, demon tail, huge ass, rio (blue archive), hair spread out, toenail polish, wolf ears, crossed legs, neck bell, sports bra, asuna (blue archive), blue jacket, missionary, micro bikini, gradient background, light brown hair, ear piercing, foreshortening, licking, light blush, meme, threesome, faceless, muscular, doggystyle, heavy breathing, sharp teeth, white socks, cumdrip, standing sex, animal print, armpit crease, o-ring, vocaloid, fins, lace trim, pasties, sandals, bag, serafuku, kiss, cum overflow, interracial, tank top, underwear only, ellen joe, facial, single braid, bdsm, fish tail, futa with female, indie virtual youtuber, red dress, rabbit girl, masturbation, shadow, wuthering waves, between breasts, cleavage cutout, ring, bottle, hatsune miku, lips, large areolae, towel, neckerchief, swept bangs, fingering, official alternate hairstyle, ?, faceless male, wide sleeves, blue ribbon, handjob, dutch angle, night, turtleneck, curtains, sound effects, standing on one leg, furrowed brow, leg up, breath, chain, scrunchie, shark tail, white jacket, nipple stimulation, straight hair, partially visible vulva, border, cum in mouth, dog ears, meme attire, plump, covering privates, firefly (honkai: star rail), head tilt, sword, wariza, abs, double-parted bangs, black halo, kantai collection, brown pantyhose, white apron, denim, low twintails, thick eyebrows, beret, white leotard, white bra, low wings, knees up, yellow halo, 1other, after vaginal, blue bikini, camisole, bondage, doodle sensei (blue archive), feathered wings, presenting armpit, yuuka (blue archive), bandaid, arm behind head, breasts squeezed together, chair, couch, drooling, panty pull, tree, character name, siblings, one side up, sleeves past wrists, undressing, black socks, pov crotch, drill hair, red bowtie, :3, eyes visible through hair, hand on own chest, holding cup, pov hands, scar, white hat, pencil skirt, black wings, inverted nipples, tanlines, 4girls, black belt, flat chest, long fingernails, mole under mouth, no pants, pink background, sash, white hairband, grabbing from behind, red bikini, boku no hero academia, legs up, lingerie, tearing up, white pantyhose, cross, plaid clothes, purple nails, dated, grabbing another's ass, hanging breasts, leash, thigh boots, blue leotard, white flower, blue shirt, holding food, holding hands, patreon logo, black background, toned, gun, watermark, bandages, web address, white bow, wolf girl, @ @, rape, shrug (clothing), strap slip, anger vein, cropped jacket, fishnet pantyhose, used condom, veil, demon wings, female masturbation, short dress, blue bowtie, mouth hold, bob cut, book, cardigan, fangs, print bikini, slit pupils, white footwear, blue dress, expressionless, shark girl, table, hug, white border, dildo, kneepits, white skirt, 2koma, jane doe (zenless zone zero), mouse ears, arm strap, armband, black collar, cow print, knee up, spread pussy, dress shirt, foot out of frame, goggles, mouse girl, neck ribbon, braided ponytail, frieren, gakuen idolmaster, head out of frame, highleg panties, long bangs, profile, wet clothes, convenient censoring, girls' frontline, partially submerged, hoodie, muscular female, tinted eyewear, eyeshadow, grey halo, head wings, highleg bikini, lactation, side slit, hair over shoulder, kneehighs, object insertion, petite, puffy nipples, tight clothes, white wrist cuffs, cropped shirt, cum on hair, flying sweatdrops, rolling eyes, sketch, top-down bottom-up, round eyewear, saliva trail, thighband pantyhose, ahegao, panties aside, trailblazer (honkai: star rail), fake horns, french kiss, licking penis, bridal gauntlets, nipple piercing, one eye covered, blue background, garter belt, condom wrapper, hoop earrings, :q, drinking glass, floral print, see-through shirt, toned female, light smile, multicolored clothes, red skirt, cow ears, plaid skirt, blue necktie, precum, depth of field, hand on another's head, orgasm, zhu yuan, adapted costume, armlet, armor, front-tie top, mechanical halo, symbol in eye, wavy mouth, frown, idolmaster shiny colors, logo, antenna hair, desk, dog girl, hairpin, high-waist skirt, sisters, umbrella, wavy hair, criss-cross halter, denim shorts, maid apron, multiple tails, single hair bun, ffm threesome, floating hair, frilled bikini, panties under pantyhose, pink panties, short eyebrows, side-tie panties, asymmetrical bangs, moaning, pink bow, bow panties, white sweater, black necktie, holding sword, kono subarashii sekai ni shukufuku wo!, messy hair, witch hat, wolf tail, black bowtie, cow horns, gyaru, nipple tweak, puffy short sleeves, sparkle, tsurime, competition swimsuit, cross-section, eyeliner, red jacket, toki (blue archive), turtleneck sweater, arm under breasts, blue shorts, median furrow, shirt tucked in, hair rings, tassel, torn thighhighs, vibrator, white one-piece swimsuit, front-tie bikini top, goggles on head, hoshimachi suisei, huge penis, id card, scarf, single side bun, sparkle (honkai: star rail), grabbing own breast, mouth mask, sunlight, crying, feathers, mouse tail, pulling own clothes, 3boys, black coat, black sailor collar, bound wrists, hina (blue archive), kisaki (blue archive), nijisanji, on couch, otoko no ko, stud earrings, vest, cape, cloudy sky, cropped legs, fern (sousou no frieren), wrist scrunchie, assertive female, black one-piece swimsuit, burnice white, cuffs, fox mask, micro shorts, tiara, tiles, alcohol, arm behind back, kazusa (blue archive), low ponytail, mari (blue archive), mask on head, candy, double v, dress lift, final fantasy, kanna (blue archive), light blue hair, looking up, backboob, butterfly hair ornament, dot nose, female ejaculation, male focus, naughty face, nicole demara, side braid, can, crossover, hair over eyes, headphones, high heel boots, partially unbuttoned, pekomama, red necktie, shiroko (blue archive), sleeping, stomach bulge, ascot, backless outfit, belle (zenless zone zero), buttons, freckles, obi, public indecency, rope, single bare shoulder, sneakers, :p, gigantic breasts, heart pasties, interlocked fingers, pantyshot, shared bathing, cowbell, female orgasm, jingle bell, legs together, strapless dress, toeless legwear, black sleeves, cow print bikini, dragon horns, gold trim, green halo, wading, capelet, cum in ass, dolphin shorts, grey shirt, half gloves, hand on own ass, karin (blue archive), office lady, presenting, cross hair ornament, navel piercing, seiza, spaghetti strap, white sleeves, dog tail, love live!, mirror, onsen, out of frame, outside border, black sports bra, furry, green jacket, hand in own hair, imminent penetration, light particles, sand, split, t-shirt, bare back, baseball cap, copyright name, facing viewer, grabbing another's hair, high-waist pants, noa (blue archive), selfie, single glove, spikes, blue panties, covering breasts, night sky, swim ring, white ribbon, black bodysuit, bound arms, buruma, chibi, fire emblem, fruit, happy sex, huge ahoge, lipstick, looking ahead, purple halo, beads, black-framed eyewear, furina (genshin impact), idolmaster cinderella girls, motion blur, on chair, open coat, forehead, fur-trimmed jacket, gold bikini, grey skirt, m legs, naked shirt, white wings, close-up, crossed arms"

In [10]:
df = new_df[:5000]
df

,id,media_asset_created_at,score,rating,media_asset_file_size,tag_string_general,tag_string_character,tag_string_copyright,image_url,tags,image_path
1,7615873,2024-05-08 20:52:36.138000+00:00,106,e,126497,1boy 1girl all_fours anal ass barefoot black_t...,megumin satou_kazuma,kono_subarashii_sekai_ni_shukufuku_wo!,https://cdn.donmai.us/360x360/04/5e/045e482079...,"[1boy, 1girl, all_fours, anal, ass, barefoot, ...",data/images/danbooru2025_val/7615873.jpg
8,7711000,2024-06-14 02:28:49.403000+00:00,83,q,3930555,1girl back backboob backless_dress backless_ou...,yor_briar,spy_x_family,https://cdn.donmai.us/360x360/36/15/3615871497...,"[1girl, back, backboob, backless_dress, backle...",data/images/danbooru2025_val/7711000.jpg
9,7570805,2024-05-12 12:43:56.579000+00:00,65,s,264075,1girl ahoge animal_ear_fluff animal_ears back_...,hina_(blue_archive) mash_kyrielight mash_kyrie...,blue_archive fate/grand_order fate_(series),https://cdn.donmai.us/360x360/3b/bb/3bbb87d7ad...,"[1girl, ahoge, animal_ear_fluff, animal_ears, ...",data/images/danbooru2025_val/7570805.jpg
10,7291029,2024-03-04 08:48:56.042000+00:00,54,s,1006806,1girl animal_ears bare_shoulders black_leotard...,hatsune_miku,rabbit_hole_(vocaloid) vocaloid,https://cdn.donmai.us/360x360/c5/48/c548a47499...,"[1girl, animal_ears, bare_shoulders, black_leo...",data/images/danbooru2025_val/7291029.jpg
11,7841062,2024-07-11 14:15:40.595000+00:00,86,q,715030,4girls ace_trainer_(pokemon)_(cosplay) antenna...,ace_trainer_(pokemon) dawn_(pokemon) hilda_(po...,pokemon pokemon_bw pokemon_bw2 pokemon_dppt po...,https://cdn.donmai.us/360x360/22/bb/22bb2ac0e9...,"[4girls, antenna_hair, blush, bow_hairband, br...",data/images/danbooru2025_val/7841062.jpg
...,...,...,...,...,...,...,...,...,...,...,...
26469,8517246,2024-12-03 16:34:48.950000+00:00,59,g,388383,1boy 1girl blush collared_shirt crossed_arms e...,wise_(zenless_zone_zero) zhu_yuan,zenless_zone_zero,https://cdn.donmai.us/360x360/3f/b7/3fb753f1eb...,"[1boy, 1girl, blush, collared_shirt, crossed_a...",data/images/danbooru2025_val/8517246.jpg
26478,8043413,2024-08-23 21:51:03.857000+00:00,295,e,1804812,1boy 1girl artist_name blush closed_eyes erect...,alexandrina_sebastiane,zenless_zone_zero,https://cdn.donmai.us/360x360/c8/15/c815e39e2a...,"[1boy, 1girl, artist_name, blush, closed_eyes,...",data/images/danbooru2025_val/8043413.jpg
26481,8277191,2024-10-11 19:21:40.072000+00:00,167,e,375463,2girls ass barbell_piercing barefoot blue_eyes...,elizabeth_(bioshock_infinite) lara_croft,bioshock_(series) bioshock_infinite tomb_raider,https://cdn.donmai.us/360x360/0a/18/0a185c4d55...,"[2girls, ass, barbell_piercing, barefoot, blue...",data/images/danbooru2025_val/8277191.jpg
26482,8507119,2024-12-01 09:25:57.320000+00:00,101,q,2464085,1girl black_hair blunt_bangs blush bodysuit br...,sabrina_(pokemon),pokemon pokemon_frlg,https://cdn.donmai.us/360x360/dd/1b/dd1bbd6173...,"[1girl, black_hair, blunt_bangs, blush, bodysu...",data/images/danbooru2025_val/8507119.jpg
26496,9026625,2025-03-20 20:02:21.147000+00:00,291,e,3769112,1boy 1girl afterimage bare_shoulders bent_over...,ayanami_(azur_lane) ayanami_(retrofit)_(azur_l...,azur_lane,https://cdn.donmai.us/360x360/c2/49/c249a3b2a7...,"[1boy, 1girl, afterimage, bare_shoulders, bent...",data/images/danbooru2025_val/9026625.jpg

In [11]:
df.to_parquet(
    "data/danbooru_after2024_testset.parquet",
    index=False,
    compression="zstd",
)