In [1]:
from datasets import load_dataset
from collections import Counter
import gc
import ast
import pandas as pd

In [12]:
full_val_df = pd.read_parquet("data/danbooru2025_val.parquet")
full_val_df

,id,media_asset_created_at,score,rating,media_asset_file_size,tag_string_general,tag_string_character,tag_string_copyright,image_url,tags,image_path
0,3803458,2020-02-29T02:04:09.022-05:00,65,s,623996,1girl antenna_hair armpits bed_sheet blush bre...,al_azif_(demonbane),demonbane,https://cdn.donmai.us/360x360/57/a8/57a82bf4a1...,"[1girl, antenna_hair, armpits, bed_sheet, blus...",data/images/danbooru2025_val/3803458.jpg
1,7615873,2024-05-08T16:52:36.138-04:00,106,e,126497,1boy 1girl all_fours anal ass barefoot black_t...,megumin satou_kazuma,kono_subarashii_sekai_ni_shukufuku_wo!,https://cdn.donmai.us/360x360/04/5e/045e482079...,"[1boy, 1girl, all_fours, anal, ass, barefoot, ...",data/images/danbooru2025_val/7615873.jpg
2,5807689,2022-11-08T06:41:09.289-05:00,99,s,295115,1girl alternate_hairstyle breasts cleavage clo...,arisugawa_natsuha,idolmaster idolmaster_shiny_colors,https://cdn.donmai.us/360x360/dd/58/dd589e8223...,"[1girl, alternate_hairstyle, breasts, cleavage...",data/images/danbooru2025_val/5807689.jpg
3,5771329,2022-10-24T13:40:25.390-04:00,135,e,2100081,1boy 1girl :o arm_grab bar_censor bouncing_bre...,,original,https://cdn.donmai.us/360x360/7e/db/7edb0f7795...,"[1boy, 1girl, :o, arm_grab, bar_censor, bounci...",data/images/danbooru2025_val/5771329.jpg
4,2987219,2018-01-14T16:47:46.466-05:00,62,q,154001,1girl armor black_panties blue_eyes blue_hair ...,nanami_yachiyo,magia_record:_mahou_shoujo_madoka_magica_gaide...,https://cdn.donmai.us/360x360/ff/7e/ff7edf51b7...,"[1girl, armor, black_panties, blue_eyes, blue_...",data/images/danbooru2025_val/2987219.jpg
...,...,...,...,...,...,...,...,...,...,...,...
99995,5599936,2022-08-17T22:49:56.764-04:00,53,s,577595,1girl ahoge animal_ears bare_legs black_skirt ...,,original,https://cdn.donmai.us/360x360/5b/62/5b620ccca4...,"[1girl, ahoge, animal_ears, bare_legs, black_s...",data/images/danbooru2025_val/5599936.jpg
99996,8643081,2024-12-31T10:01:59.979-05:00,143,e,9777813,1boy 1girl :q against_glass anus ass breasts c...,kita_ikuyo,bocchi_the_rock!,https://cdn.donmai.us/360x360/c6/73/c673f9a7f9...,"[1boy, 1girl, :q, against_glass, anus, ass, br...",data/images/danbooru2025_val/8643081.jpg
99997,6042767,2023-02-04T16:56:08.190-05:00,231,e,5237793,1boy 1girl ? animal_ears anus ass bar_censor b...,tsunomaki_watame,hololive,https://cdn.donmai.us/360x360/e9/3a/e93ae304c9...,"[1boy, 1girl, ?, animal_ears, anus, ass, bar_c...",data/images/danbooru2025_val/6042767.jpg
99998,5870341,2022-12-03T09:46:20.261-05:00,52,s,604539,1girl body_freckles bra bracelet breasts cleav...,beelzebub_(helltaker),helltaker,https://cdn.donmai.us/360x360/22/0b/220bd87446...,"[1girl, body_freckles, bra, bracelet, breasts,...",data/images/danbooru2025_val/5870341.jpg
99999,7823524,2024-07-07T11:00:01.122-04:00,134,q,2073475,1girl black_footwear black_pantyhose breasts f...,ellen_joe,zenless_zone_zero,https://cdn.donmai.us/360x360/82/43/82433ce2bb...,"[1girl, black_footwear, black_pantyhose, breas...",data/images/danbooru2025_val/7823524.jpg

In [13]:
# convert the datetime col
full_val_df["media_asset_created_at"] = pd.to_datetime(
    full_val_df["media_asset_created_at"],
    utc=True,
)

In [14]:
# get all tags from a DF
def get_tags(df_):
    all_tags = Counter()
    for tags in df_["tags"]:
        all_tags.update(tags)
    return all_tags

In [15]:
# all tags before 2022
old_df = full_val_df[full_val_df["media_asset_created_at"].dt.year <= 2021]
old_tags = get_tags(old_df)
len(old_tags)

10445

In [16]:
# all tags after 2023
num_samples = 5000
new_df = full_val_df[full_val_df["media_asset_created_at"].dt.year >= 2023][:num_samples]
new_tags = get_tags(new_df)
len(new_tags)

8439

In [17]:
# get common tags between them
full_tags = {tag for tag in new_tags if tag in old_tags}
len(full_tags)

7612

In [18]:
# most popular tags
stags = sorted((-c, t) for t, c in new_tags.items())
stags = [t.replace("_", " ") for c, t in stags][:1000]
", ".join(stags)

"1girl, breasts, long hair, solo, looking at viewer, blush, large breasts, smile, open mouth, navel, nipples, thighs, simple background, cleavage, black hair, 1boy, hair ornament, blue eyes, white background, bare shoulders, ass, animal ears, shirt, hetero, blue archive, hair between eyes, short hair, gloves, very long hair, underwear, collarbone, thighhighs, nude, multicolored hair, red eyes, sweat, jewelry, censored, halo, long sleeves, penis, blonde hair, swimsuit, closed mouth, sitting, multiple girls, skirt, panties, medium breasts, purple eyes, holding, tail, bikini, pussy, brown hair, standing, heart, dress, blue hair, stomach, sex, original, white shirt, indoors, virtual youtuber, sidelocks, jacket, bow, pink hair, white hair, huge breasts, lying, solo focus, 2girls, grey hair, official alternate costume, alternate costume, pantyhose, twintails, purple hair, green eyes, completely nude, yellow eyes, earrings, choker, cowboy shot, small breasts, ahoge, ponytail, tongue, horns, ribbon, teeth, hololive, parted lips, mosaic censoring, braid, cum, black gloves, full body, red hair, vaginal, spread legs, hat, mole, open clothes, tongue out, dark skin, outdoors, leotard, feet, from behind, brown eyes, genshin impact, barefoot, artist name, on back, uncensored, bar censor, pointy ears, streaked hair, armpits, black thighhighs, medium hair, toes, shorts, hairband, looking back, speech bubble, pubic hair, nail polish, rabbit ears, flower, black choker, closed eyes, pov, bra, fake animal ears, hair ribbon, black skirt, two-tone hair, upper body, english text, anus, animal ear fluff, hairclip, thigh strap, highleg, clothes lift, black panties, sky, hair over one eye, sleeveless, blunt bangs, elbow gloves, dark-skinned female, school uniform, symbol-shaped pupils, pleated skirt, grin, bowtie, off shoulder, black pantyhose, sideboob, skindentation, legs, playboy bunny, white thighhighs, covered navel, female pubic hair, blurry, detached sleeves, high heels, honkai (series), midriff, erection, thick thighs, collared shirt, arms up, hair bun, mole under eye, on bed, soles, day, hand up, strapless, white gloves, black bikini, detached collar, pink eyes, wet, green hair, azur lane, crop top, multiple views, short sleeves, testicles, :d, colored inner hair, frills, wings, one eye closed, honkai: star rail, hair flower, cat ears, fingernails, pants, cum in pussy, covered nipples, pussy juice, white panties, black jacket, groping, see-through clothes, black footwear, blue sky, collar, hair bow, hair intakes, black dress, blurry background, fate (series), necklace, fang, glasses, hololive english, upper teeth only, necktie, feet out of frame, grey background, open jacket, monochrome, orange hair, twitter username, pillow, zenless zone zero, clothing cutout, oral, groin, sex from behind, bracelet, sweatdrop, cloud, arm up, socks, fate/grand order, fingerless gloves, heart-shaped pupils, bare legs, from side, white dress, belt, looking at another, miniskirt, patreon username, strapless leotard, black leotard, parted bangs, fox ears, japanese clothes, weapon, piercing, straddling, water, white bikini, yuri, cum on body, tattoo, fellatio, signature, bare arms, saliva, shoes, v, back, torn clothes, wrist cuffs, sweater, black shirt, multiple boys, areola slip, bed sheet, boots, food, goddess of victory: nikke, short shorts, underboob, greyscale, toenails, ass visible through thighs, comic, 3girls, highleg leotard, one-piece swimsuit, grabbing another's breast, halterneck, cameltoe, girl on top, bottomless, eyewear on head, pokemon, black bra, dark-skinned male, squatting, alternate breast size, gradient hair, grey eyes, leaning forward, black shorts, clothed female nude male, black nails, blue halo, breasts out, motion lines, side-tie bikini bottom, coat, sunglasses, ass focus, hands up, shiny skin, bent over, embarrassed, fox girl, group sex, kimono, no panties, orange eyes, arknights, black hairband, side ponytail, two side up, futanari, clothes pull, curvy, demon horns, no bra, phone, steaming body, cup, sailor collar, sleeveless dress, cat tail, on side, puffy sleeves, shirt lift, ejaculation, extra ears, lifting own clothes, maid headdress, no shoes, nose blush, rabbit tail, thigh gap, beach, from above, black bow, bound, clothed sex, half-closed eyes, trembling, aqua eyes, fur trim, open shirt, arm support, eyelashes, mole on breast, revealing clothes, star (symbol), cowgirl position, male pubic hair, sex toy, double bun, topless, hood, ocean, colored skin, bed, cat girl, pelvic curtain, fox tail, twin braids, breasts apart, cosplay, garter straps, idolmaster, large penis, spoken heart, string bikini, striped clothes, veins, gradient background, kneeling, paizuri, wolf ears, all fours, black eyes, cellphone, clothing aside, ear piercing, heterochromia, holding weapon, makeup, chinese clothes, elf, from below, red nails, demon girl, red bow, sleeveless shirt, bell, crossed legs, tears, touhou, turtleneck, wide hips, wide sleeves, window, anal, black ribbon, fake tail, skirt lift, blue skirt, hand on own hip, mature female, red ribbon, bright pupils, clenched teeth, crossed bangs, pink halo, 2boys, condom, kantai collection, on stomach, apron, bag, muscular, red halo, serafuku, arms behind back, arms behind head, blue bow, blue jacket, facial mark, lips, micro bikini, :o, fishnets, restrained, steam, bodysuit, huge ass, looking down, o-ring, sousou no frieren, black pants, cumdrip, heavy breathing, maid, bdsm, blue nails, looking to the side, x hair ornament, after sex, brown pantyhose, demon tail, ring, veiny penis, black horns, head tilt, skin fang, smartphone, swept bangs, v-shaped eyebrows, foreshortening, sandals, shadow, white socks, blue leotard, breast press, handjob, high ponytail, mask, towel, underwear only, alternate hairstyle, animal print, china dress, cleavage cutout, lace trim, light brown hair, thong, white pupils, between breasts, bouncing breasts, cum on breasts, large areolae, covering privates, dutch angle, facial, hair spread out, neck bell, single braid, toenail polish, torn pantyhose, web address, white jacket, holding phone, low twintails, missionary, straight hair, white footwear, licking, masturbation, meme attire, sensei (blue archive), sharp teeth, kiss, knees up, neckerchief, one side up, pasties, scrunchie, sleeves past wrists, threesome, tree, black hat, breath, chair, curtains, meme, sports bra, wariza, yuuka (blue archive), beret, border, chain, cleft of venus, mole under mouth, standing on one leg, denim, dog ears, futa with female, leg up, light blush, tan, asuna (blue archive), bondage, cum overflow, flat chest, official alternate hairstyle, patreon logo, single thighhigh, blue ribbon, cross, doggystyle, feathered wings, furrowed brow, slit pupils, wet clothes, bob cut, foot focus, plump, scar, white skirt, asymmetrical bangs, bottle, kneepits, tearing up, abs, blue shirt, drill hair, faceless, fingering, legs up, low wings, night, shirt tucked in, standing sex, sword, wavy hair, couch, cum in mouth, grabbing from behind, mechanical halo, partially submerged, raised eyebrows, sound effects, thigh boots, white flower, aqua hair, bandaid, black socks, indie virtual youtuber, sash, strap slip, thick eyebrows, veil, armlet, book, female masturbation, kneehighs, lingerie, plaid clothes, rape, thighband pantyhose, after vaginal, grabbing another's ass, hug, long fingernails, panty pull, pencil skirt, red dress, round eyewear, short dress, tank top, :3, armband, black wings, camisole, faceless male, pink nails, pov hands, white leotard, wolf girl, breasts squeezed together, doodle sensei (blue archive), foot out of frame, hoodie, nijisanji, rio (blue archive), table, white border, arm behind head, armor, armpit crease, blue bowtie, character name, dated, dress shirt, drooling, holding cup, panties aside, profile, puffy nipples, toned, turtleneck sweater, watermark, 1other, blue bikini, depth of field, expressionless, gun, hanging breasts, long bangs, multicolored clothes, nipple stimulation, scarf, shrug (clothing), ascot, blue dress, bow panties, bridal gauntlets, cropped legs, fake horns, gyaru, idolmaster shiny colors, interracial, muscular female, neck ribbon, partially visible vulva, toki (blue archive), undressing, ?, black belt, boku no hero academia, competition swimsuit, cropped jacket, dildo, double-parted bangs, hand on own chest, holding food, open coat, red skirt, siblings, spikes, spread pussy, white bra, cardigan, cropped shirt, fins, highleg bikini, highleg panties, holding hands, cape, convenient censoring, demon wings, eyes visible through hair, frilled bikini, garter belt, head wings, mouth hold, nun, rabbit girl, white sleeves, 4girls, @ @, antenna hair, black background, black bowtie, butterfly hair ornament, buttons, male focus, otoko no ko, pov crotch, print bikini, red bowtie, side-tie panties, tassel, used condom, white apron, alcohol, desk, drinking glass, fangs, floating hair, girls' frontline, hair rings, knees together feet apart, no pants, plaid skirt, trailblazer (honkai: star rail), wavy mouth, white sweater, 2koma, blue necktie, bocchi the rock!, fern (sousou no frieren), fish tail, fishnet pantyhose, french kiss, frown, knee up, licking penis, light blue hair, logo, one eye covered, pantyshot, pink panties, raiden shogun, red bikini, vibrator, wooden floor, :p, cloudy sky, denim shorts, double v, fire emblem, goggles, gold trim, hand on another's head, inverted nipples, light smile, messy hair, one breast out, red necktie, rolling eyes, shiroko (blue archive), side slit, tiara, yellow halo, buruma, cow print, eyeshadow, floral print, flying sweatdrops, frieren, hand on own face, head out of frame, headphones, leash, pink bikini, pink bow, puffy short sleeves, sketch, wading, white bow, white hairband, arm strap, assertive female, baseball cap, black collar, legs together, mirror, nipple tweak, object insertion, orgasm, outside border, presenting, sparkle, vest, white pantyhose, wolf tail, black coat, black one-piece swimsuit, can, condom wrapper, cum in ass, cum on hair, ellen joe, gym uniform, kisaki (blue archive), lace-trimmed bra, median furrow, mismatched pupils, mouse girl, muscular male, obi, public indecency, semi-rimless eyewear, top-down bottom-up, 3boys, ahegao, arm tattoo, bandages, bulge, dog girl, dragon horns, furina (genshin impact), highleg one-piece swimsuit, navel piercing, nipple piercing, pokemon (creature), ribbed sweater, shared bathing, sneakers, tinted eyewear, umbrella, white ribbon, white wrist cuffs, anger vein, bikini under clothes, cross-section, gangbang, hair scrunchie, hoop earrings, kafka (honkai: star rail), kanna (blue archive), maid apron, moaning, partially unbuttoned, short hair with long locks, skin tight, tight clothes, track jacket, vocaloid, white one-piece swimsuit, black sailor collar, braided ponytail, chainsaw man, covering breasts, dress lift, folded, front-tie top, goggles on head, hair over eyes, heart pasties, high-waist skirt, imminent penetration, micro shorts, mouse ears, ouro kronii, plant, puffy long sleeves, seiza, shark tail, single side bun, sleeves rolled up, tanlines, thighlet, tiles, ..., :q, blue shorts, capelet, chibi, close-up, clothes writing, colored sclera, crying, cuffs, eyeliner, ganyu (genshin impact), height difference, hu tao (genshin impact), kazusa (blue archive), love live!, motion blur, on couch, onsen, pink background, purple nails, sand, school swimsuit, side braid, sisters, stomach bulge, surprised, artist logo, belly, blue one-piece swimsuit, bound wrists, copyright name, cross hair ornament, dolphin shorts, feet up, final fantasy, forehead, happy sex, leaf, licking lips, looking up, mari (blue archive), multiple tails, naughty face, office lady, on floor, petite, reflection, rope, vision (genshin impact), white hat, angel wings, arm behind back, ball, black necktie, blood, bodystocking, brown thighhighs, couple, cow print bikini, crossed arms, dragon print, empty eyes, facing viewer, female orgasm, hair over shoulder, hatsune miku, huge penis, impossible clothes, interlocked fingers, linea alba, noa (blue archive), out of frame, own hands together, purple flower, red jacket, red panties, shoulder cutout, symbol in eye, the legend of zelda, white wings, yae miko, ^ ^, arm under breasts, backboob, backless outfit, bags under eyes, between legs, blue background, contrapposto, cow horns, criss-cross halter, ear blush, firefly (honkai: star rail), frilled dress, fruit, gag, gem, grabbing own breast, grey shirt, hairpin, hand in own hair, headband, holding another's wrist, holding gun, holding sword, hood down, hooded jacket, lactation, low ponytail, mouth mask, panties under pantyhose, rose, sakamata chloe, selfie, sleeping, torso grab, white coat, zipper, bikini top only"

In [19]:
# Keep only common tags
df = new_df.copy()
df["tags"] = df["tags"].apply(
    lambda tags: [tag for tag in tags if tag in full_tags]
)

# Remove images with no remaining tags
df = df[df["tags"].str.len() > 0]

# (Optional) Remove images with only one tag
df = df[df["tags"].str.len() >= 2]

df = df.reset_index(drop=True)
df

,id,media_asset_created_at,score,rating,media_asset_file_size,tag_string_general,tag_string_character,tag_string_copyright,image_url,tags,image_path
0,7615873,2024-05-08 20:52:36.138000+00:00,106,e,126497,1boy 1girl all_fours anal ass barefoot black_t...,megumin satou_kazuma,kono_subarashii_sekai_ni_shukufuku_wo!,https://cdn.donmai.us/360x360/04/5e/045e482079...,"[1boy, 1girl, all_fours, anal, ass, barefoot, ...",data/images/danbooru2025_val/7615873.jpg
1,7711000,2024-06-14 02:28:49.403000+00:00,83,q,3930555,1girl back backboob backless_dress backless_ou...,yor_briar,spy_x_family,https://cdn.donmai.us/360x360/36/15/3615871497...,"[1girl, back, backboob, backless_dress, backle...",data/images/danbooru2025_val/7711000.jpg
2,7570805,2024-05-12 12:43:56.579000+00:00,65,s,264075,1girl ahoge animal_ear_fluff animal_ears back_...,hina_(blue_archive) mash_kyrielight mash_kyrie...,blue_archive fate/grand_order fate_(series),https://cdn.donmai.us/360x360/3b/bb/3bbb87d7ad...,"[1girl, ahoge, animal_ear_fluff, animal_ears, ...",data/images/danbooru2025_val/7570805.jpg
3,7291029,2024-03-04 08:48:56.042000+00:00,54,s,1006806,1girl animal_ears bare_shoulders black_leotard...,hatsune_miku,rabbit_hole_(vocaloid) vocaloid,https://cdn.donmai.us/360x360/c5/48/c548a47499...,"[1girl, animal_ears, bare_shoulders, black_leo...",data/images/danbooru2025_val/7291029.jpg
4,7841062,2024-07-11 14:15:40.595000+00:00,86,q,715030,4girls ace_trainer_(pokemon)_(cosplay) antenna...,ace_trainer_(pokemon) dawn_(pokemon) hilda_(po...,pokemon pokemon_bw pokemon_bw2 pokemon_dppt po...,https://cdn.donmai.us/360x360/22/bb/22bb2ac0e9...,"[4girls, antenna_hair, blush, bow_hairband, br...",data/images/danbooru2025_val/7841062.jpg
...,...,...,...,...,...,...,...,...,...,...,...
4995,6360048,2023-01-23 14:18:05.099000+00:00,93,e,2601736,1girl animal_ears belly blush bottomless bra b...,ookami_mio,hololive,https://cdn.donmai.us/360x360/b2/9f/b29fe368d4...,"[1girl, animal_ears, belly, blush, bottomless,...",data/images/danbooru2025_val/6360048.jpg
4996,6294706,2023-05-09 19:40:58.041000+00:00,382,e,94775,1girl anus ass blush borrowed_character bow bo...,alcremie alcremie_(strawberry_sweet) alcremie_...,pokemon pokemon_swsh,https://cdn.donmai.us/360x360/23/4b/234b995dd7...,"[1girl, anus, ass, blush, borrowed_character, ...",data/images/danbooru2025_val/6294706.jpg
4997,6525406,2023-07-25 05:04:04.555000+00:00,169,e,5202352,1girl anus armpits artist_name ass bag black_b...,satonaka_megumi_(futamotu),original,https://cdn.donmai.us/360x360/43/af/43afcdda95...,"[1girl, anus, armpits, artist_name, ass, bag, ...",data/images/danbooru2025_val/6525406.jpg
4998,5983065,2023-01-14 19:48:32.033000+00:00,68,s,3009462,1girl alternate_costume arm_up armpits blonde_...,durandal_(dea_anchora)_(honkai_impact) duranda...,honkai_(series) honkai_impact_3rd,https://cdn.donmai.us/360x360/e0/1f/e01fce810f...,"[1girl, alternate_costume, arm_up, armpits, bl...",data/images/danbooru2025_val/5983065.jpg
4999,7081003,2024-01-10 20:04:03.414000+00:00,65,s,382719,1girl bra breasts cleavage frog_girl green_bra...,asui_tsuyu,boku_no_hero_academia,https://cdn.donmai.us/360x360/26/af/26af4a8af0...,"[1girl, bra, breasts, cleavage, frog_girl, gre...",data/images/danbooru2025_val/7081003.jpg

In [20]:
df.to_parquet(
    "data/danbooru_after2023_testset.parquet",
    index=False,
    compression="zstd",
)